a = input("Please enter a number in word format: ")
b = input("Choose; friend, pet_________, or enemy: ")
c = input("Please enter a name: ")
d = input("Please enter a place: ")
e = input("Please enter a verb ending with -ed: ")
f = input("Choose a word out of the following; Good, Decent, Horrid, Smelly, The best thing ever, or Diaper: ")
g = input("Please enter a food: ")
print("your madlib;")
print(a,"day,me and my",b,"named",c,"went to",d,"and",e,".afterwards, we ate. the food was",f,". we had",g,".")
